apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aping-session
  namespace: prod
spec:
  encryptedData:
    SESSION_SECRET: AgCsLbnbImQfYWEpJ34YFoo7ht5PJ35EDoaE3uqYk8Sio9mfabTKxxWQHcwkLRK2r6ljFSfQXryGFWbQ3HBhxQBkLjE33tyr9PJNw13FiUoEUVXvhE5VaA+l/zQ1qI1S6mRRFo93ZucmuqZaBXDf4swI8rNoAP5THXxwjDjTKMnzeruLHMy+8Cny3WKAv0WNAnBxgcbX4dDxwJsFAuHXW2x6zFKgBFd7JdP8X1rgkP+UPbHMg2Zp19kgMHFhoB1m+7RtzvINA5Bh72Hgkft0elsvar3mHl0/JexokmBXkx3plXH22+Pv00wUp4KoCRBbYI1szuXcSbA7T9TLYMXJS91tHa97YyBfyBYpnFmoVYLs2dMf4mkpw/McTM0YXehABolvw3udp3fMcJaPtdyKhfE3E5SqGmzXQltf/ZeHDeEsNCQBj6sp8Mh0Mfcfd5m9aYI6sOPmfP3K51y4L2tvLHiyqNS6GDRVs13iOtVrF/gWr9fX37/Mo6USZIwKXz6YLAbT/ddzFU+cN3NBNJi+jgwt4Mo+mGhcTJQyKGQ243U5ntbtGIcG7O/FEADWcd2s5/5rrOOt/WKoG13pWAPb4S1Ylk/HE6/qd9ifUKfFQRbdFIxUXvmj93QdHl9b1cJQT6GFuDC532K9JEgUBzYaMPbJX0NhvdzpUCAHNulgDE4WtChI/VoMUp5zYux7cKMvI1UN0siKwDYE5YjQGjM4emrDl841CeRGBOQ0vAzdui8roK1B/Y5thEDO9sUkwGCqZa4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aping-session
      namespace: prod

