apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: denartcc/api
  newName: denartcc/api
  newTag: 945f1f4
patchesStrategicMerge:
- api/merge/ingress.yaml
patchesJson6902:
  - path: cluster-manager/cluster-issuer-path.yaml
    target:
      group: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt
      version: v1