apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{ .Release.Namespace }}
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
{{- if contains "/" .Values.image }}
        image: "{{ .Values.image }}"
{{- else }}
        image: "{{ .Values.hub | default .Values.global.hub }}/{{ .Values.image | default "auth" }}:{{ .Values.tag | default .Values.global.tag }}"
{{- end }}
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: auth-env-db
            optional: false
        - secretRef:
            name: auth-env-vatsim
            optional: false
        - secretRef:
            name: auth-env-jwks
            optional: false
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 3
        resources:
          {{ toYaml .Values.resources | trim | nindent 10 }}