apiVersion: v1
kind: Secret
metadata:
  name: auth-env-db
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.database.host | b64enc }}
  DB_PORT: {{ .Values.database.port | toString | b64enc }}
  DB_DATABASE: {{ .Values.database.database | b64enc }}
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-env-vatsim
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  VATSIM_OAUTH_CLIENT_ID: {{ .Values.oauth.client_id | b64enc }}
  VATSIM_OAUTH_CLIENT_SECRET: {{ .Values.oauth.client_secret | b64enc }}
  VATSIM_BASE_URL: {{ .Values.oauth.base_url | b64enc }}
  VATSIM_AUTHORIZE_PATH: {{ .Values.oauth.authorize_path | b64enc }}
  VATSIM_TOKEN_PATH: {{ .Values.oauth.token_path | b64enc }}
  VATSIM_USER_INFO_PATH: {{ .Values.oauth.userinfo_path | b64enc }}
  VATSIM_OAUTH_SCOPES: {{ .Values.oauth.scopes | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-env-jwks
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  SSO_JWKS: {{ .Values.jwks | b64enc }}