enabled: true
hub: ""
image: auth
tag: ""

appkey: ""

database:
  host: "mysql.mysql.svc.cluster.local"
  port: 3306
  database: "prod_v2"
  username: "web"
  password: "web"
oauth:
  client_id: "12345"
  client_secret: "secret"
  base_url: "https://auth.vatsim.net"
  authorize_path: "/oauth/authorize"
  token_path: "/oauth/token"
  userinfo_path: "/api/user"
  scopes: "full_name email"
jwks: ''
ingress:
  ingressClassName: "nginx"
  hosts:
  - "auth.denartcc.org"
  tlsSecret: "auth-tls"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
