apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  config.yaml: |
    server:
      port: 3000
      host: 127.0.0.1
    database:
      host: {{.DB_HOST | default "mysql.mysql.svc.cluster.local"}}
      port: 3306
      user: {{.DB_USER | default "root"}}
      password: {{.DB_PASSWORD | default "root"}}
      database: {{.DB_DATABASE | default "zdv"}}
      automigrate: true
    discord:
      webhooks:
        events: {{.DISCORD_WEBHOOK_EVENTS}}
        seniorstaff: {{.DISCORD_WEBHOOK_SENIORSTAFF}}
        staffup: {{.DISCORD_WEBHOOK_STAFFUP}}
        training: {{.DISCORD_WEBHOOK_TRAINING}}
        default: {{.DISCORD_WEBHOOK_DEFAULT}}
    email:
      host: {{.EMAIL_HOST | default "localhost"}}
      port: {{.EMAIL_PORT | default "25"}}
      user: {{.EMAIL_USER | default "root"}}
      password: {{.EMAIL_PASSWORD | default "root"}}
      from: {{.EMAIL_FROM | default "root@localhost"}}
    rabbitmq:
      host: {{.RABBITMQ_HOST | default "rabbitmq.rabbitmq.svc.cluster.local"}}
      port: {{.RABBITMQ_PORT | default 5672}}
      user: {{.RABBITMQ_USER | default "guest"}}
      password: {{.RABBITMQ_PASSWORD | default ""}}
    session:
      cookie:
        name: "zdv_session"
        secret: "{{.SESSION_SECRET | default "secret"}}"
        max_age: 604800
        domain: ".denartcc.org"
        path: "/"
    oauth:
      base_URL: "https://auth.denartcc.org"
      endpoints:
        token: "/oauth/token"
        user: "/v1/user"
        authorize: "/oauth/authorize"
      client_id: "{{.OAUTH_CLIENT_ID | default "zdv"}}"
      client_secret: "{{.OAUTH_CLIENT_SECRET | default "zdv"}}"
      my_base_URL: "https://api.denartcc.org"