apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: nextgen
data:
  config.yaml: |
    server:
      port: 3000
      host: 127.0.0.1
    database:
      host: {{.DB_HOST | default "mysql.mysql.svc.cluster.local"}}
      port: 3306
      user: {{.DB_USER | default "root"}}
      password: {{.DB_PASSWORD | default "root"}}
      database: {{.DB_DATABASE | default "zdv"}}
      automigrate: true
    email:
      host: {{.EMAIL_HOST | default "localhost"}}
      port: {{.EMAIL_PORT | default "25"}}
      user: {{.EMAIL_USER | default "root"}}
      password: {{.EMAIL_PASSWORD | default "root"}}
      from: {{.EMAIL_FROM | default "root@localhost"}}
    rabbitmq:
      host: {{.RABBITMQ_HOST | default "rabbitmq.rabbitmq.svc.cluster.local"}}
      port: {{.RABBITMQ_PORT | default 5672}}
      user: {{.RABBITMQ_USER | default "guest"}}
      password: {{.RABBITMQ_PASSWORD | default ""}}
    redis:
      address: {{.REDIS_HOST | default "redis.redis.svc.cluster.local:6379"}}
      database: 0
      password: {{.REDIS_PASSWORD | default "secret"}}
      sentinel: {{.REDIS_SENTINEL | default false}}
      master_name: {{.REDIS_MASTER_NAME | default "master"}}
      # sentinel_addrs is an array that cannot be easily expressed in shell... use config map
      sentinel_addrs:
        - "{{.REDIS_SENTINEL_HOST | default "redis.redis.svc.cluster.local:26379"}}"
    session:
      cookie:
        name: "{{.SESSION_NAME | default "zdv_session"}}"
        key: "{{.SESSION_KEY | default "zdv_session"}}"
        max_age: 604800
        domain: "{{.SESSION_DOMAIN | default ".denartcc.org"}}"
        path: "/"
    storage:
      access_key: {{.STORAGE_ACCESS_KEY | default "12345"}}
      secret_key: {{.STORAGE_SECRET_KEY | default "12345"}}
      bucket: {{.STORAGE_BUCKET | default "denartcc"}}
      region: {{.STORAGE_REGION | default "us-east-1"}}
      endpoint: {{.STORAGE_ENDPOINT | default ""}}
    oauth:
      base_URL: "https://auth.denartcc.org"
      endpoints:
        token: "/oauth/token"
        user: "/v1/info"
        authorize: "/oauth/authorize"
      client_id: "{{.OAUTH_CLIENT_ID | default "zdv"}}"
      client_secret: "{{.OAUTH_CLIENT_SECRET | default "zdv"}}"
      my_base_URL: "{{.OAUTH_MY_BASE_URL | default "https://api.dev.denartcc.org" }}"
    vatusa:
      apiKey: "{{.VATUSA_API_KEY | default "zdv"}}"
