# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  hub: docker.io/denartcc
  tag: latest
  certmanager:
    issuer:
      name: letsencrypt
      kind: ClusterIssuer

bot:
  enabled: true
  discordToken: ""
  api:
    fetchMembers: "https://www.denartcc.org/getRoster"

currWeb:
  enabled: true
  database:
    driver: "mysql"
    host: "mysql.mysql.svc.cluster.local"
    port: 3306
    database: "artcc_site"
    database_forum: "artcc_forum"
    username: "web"
    password: "web"
  discord:
    oauth:
      id: "12345"
      secret: "secret"
  vatusa:
    api_key: "12345"
    uls:
      jwk: b
      url_id: 1
      redirect: "https://www.denartcc.org"
  mail:
    driver: "smtp"
    host: "smtp.gmail.com"
    port: 587
    encryption: "tls"
    username: "no-reply@denartcc.org"
    password: ""
  recaptcha:
    key: "12345"
    secret: ""

flightparser:
  enabled: true
  database:
    host: "mysql.mysql.svc.cluster.local"
    port: 3306
    database: "dev_v2"
    username: "web"
    password: "web"

api:
  enabled: true
  hub: ""
  image: api
  tag: ""

  appkey: ""

  ingress:
    ingressClassName: "nginx"
    hosts:
    - "api.denartcc.org"
    tlsSecret: "api-tls"

  database:
    host: "mysql.mysql.svc.cluster.local"
    port: 3306
    database: "prod_v2"
    username: "web"
    password: "web"
  discord:
    oauth:
      id: "12345"
      secret: "secret"
  vatusa:
    api_key: "12345"
    uls:
      jwk: "b"
      url_id: 1
      redirect: "https://www.denartcc.org"
  mail:
    driver: "smtp"
    host: "smtp.gmail.com"
    port: 587
    encryption: "tls"
    username: "no-reply@denartcc.org"
    password: ""

  resources:
    requests:
      cpu: 250m
      memory: 256Mi

auth:
  enabled: true
  database:
    host: "mysql.mysql.svc.cluster.local"
    port: 3306
    database: "prod_v2"
    username: "web"
    password: "web"
  oauth:
    client_id: "12345"
    client_secret: "secret"
    base_url: "https://auth.vatsim.net"
    authorize_path: "/oauth/authorize"
    token_path: "/oauth/token"
    userinfo_path: "/api/user"
    scopes: "full_name email"
  jwks: ''