apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- api/secret-db.yaml
- api/secret-discord.yaml
- api/secret-email.yaml
- api/secret-oauth.yaml
- api/secret-rabbitmq.yaml
- api/secret-session.yaml
images:
- name: denartcc/api
  newName: adhp/api
  newTag: 6711e3a
- name: denartcc/api:411c810
  newName: denartcc/api
  newTag: fe44c92
