apiVersion: v1
kind: Secret
metadata:
  name: web-env-app-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  APP_KEY: {{ .Values.appkey | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: web-env-db
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_CONNECTION: {{ .Values.database.driver | b64enc }}
  DB_HOST: {{ .Values.database.host | b64enc }}
  DB_PORT: {{ .Values.database.port | toString | b64enc }}
  DB_DATABASE: {{ .Values.database.database | b64enc }}
  DB_DATABASE_FORUM: {{ .Values.database.database_forum | b64enc }}
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: web-env-discord
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DISCORD_CLIENT_ID: {{ .Values.discord.oauth.id | b64enc }}
  DISCORD_CLIENT_SECRET: {{ .Values.discord.oauth.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: web-env-vatusa
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  VATUSA_API: {{ .Values.vatusa.api_key | b64enc }}
  VATUSA_ULS_JWK: {{ .Values.vatusa.uls.jwk | b64enc }}
  VATUSA_ULS_URL_ID: {{ .Values.vatusa.uls.url_id | toString | b64enc }}
  VATUSA_ULS_REDIRECT: {{ .Values.vatusa.uls.redirect | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: web-env-mail
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  MAIL_DRIVER: {{ .Values.mail.driver | b64enc }}
  MAIL_HOST: {{ .Values.mail.host | b64enc }}
  MAIL_PORT: {{ .Values.mail.port | toString | b64enc }}
  MAIL_ENCRYPTION: {{ .Values.mail.encryption | b64enc }}
  MAIL_USERNAME: {{ .Values.mail.username | b64enc }}
  MAIL_PASSWORD: {{ .Values.mail.password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: web-env-recaptcha
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  RECAPTCHA_KEY: {{ .Values.recaptcha.key | b64enc }}
  RECAPTCHA_SECRET: {{ .Values.recaptcha.secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: web-env-discord-webhooks
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DISCORD_LOGO: {{ .Values.discord.logo | default "https://cdn.denartcc.org/assets/img/logo512.png" | b64enc }}
  DISCORD_WEBHOOK_EVENTS_ANNOUNCEMENTS: {{ .Values.discord.webhooks.events_announcements | b64enc }}
  DISCORD_WEBHOOK_STAFFUP: {{ .Values.discord.webhooks.staffup | b64enc }}
  DISCORD_WEBHOOK_DEFAULT: {{ .Values.discord.webhooks.default | b64enc }}