apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-kzdv
resources:
- cert-manager/cluster-issuer.yaml
- api/certificate.yaml
- api/configmap.yaml
- api/deployment-api.yaml
- api/deployment-runner.yaml
- api/service.yaml
- api/ingress.yaml