apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: curr-web
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - backend:
          service:
            name: curr-web
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- end }}
  tls:
  - hosts:
    {{- range .Values.ingress.hosts }}
      - {{ . }}
    {{- end }}
    secretName: {{ .Values.ingress.tlsSecret }}
