apiVersion: v1
kind: Secret
metadata:
  name: flight-parser-env-db
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_HOST: {{ .Values.database.host | b64enc }}
  DB_PORT: {{ .Values.database.port | toString | b64enc }}
  DB_DATABASE: {{ .Values.database.database | b64enc }}
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}