apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- api/sealed-secret-db.yaml
- api/sealed-secret-discord.yaml
- api/sealed-secret-email.yaml
- api/sealed-secret-oauth.yaml
- api/sealed-secret-redis.yaml
- api/sealed-secret-rabbitmq.yaml
- api/sealed-secret-session.yaml
- api/sealed-secret-storage.yaml
- api/sealed-secret-vatusa.yaml
images:
- name: denartcc/api
  newName: adhp/api
  newTag: ba92ec0
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
