apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- api/secret-db.yaml
- api/secret-discord.yaml
- api/secret-email.yaml
- api/secret-oauth.yaml
- api/secret-rabbitmq.yaml
- api/secret-session.yaml
images:
- name: denartcc/api
  newName: denartcc/api
  newTag: 8f32cf33
patchesStrategicMerge:
- api/merge/certificate.yaml
